# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#This shall as well send coverage to codecov.io to generate a badge with a percentage of done tests

name: raedar CI/CD jobs

on:
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x,13.x]

    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
               
    - name: Coveralls
      uses: codecov/codecov-action@v1
      with: 
        token: ${{ secrets.a9182f60-bde1-4016-9a66-72e745774dd7 }} # not required for public repos
        file: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)

    - run: yarn
    - run: yarn run build
    - run: yarn run test:unit
    - run: yarn  test:unit --coverage
    - run: bash <(curl -s https://codecov.io/bash)


      env:
        CI: true